---
###########################
# Common
###########################
compatibility_version: 4.1

# Data center
data_center_name: "{{ rhv_data_center | default('Default') }}"

##########################
# VM infra
##########################
template_cluster: "{{ rhv_cluster }}"
template_name: rhel7
template_memory: 4GiB
template_cpu: 1
template_disk_storage: "{{ rhv_data_storage }}"
template_disk_size: 30GiB
template_nics:
  - name: nic1
    profile_name: ovirtmgmt
    interface: virtio

master_vm:
  cluster: "{{ rhv_cluster }}"
  template: rhel7
  memory: 4GiB
  cores: 2
  high_availability: true
  disks:
    - size: 20GiB
      storage_domain: "{{ rhv_data_storage }}"
      name: docker_disk
      interface: virtio

node_vm:
  cluster: "{{ rhv_cluster }}"
  template: rhel7
  memory: 8GiB
  cores: 2
  disks:
    - size: 20GiB
      storage_domain: "{{ rhv_data_storage }}"
      name: docker_disk
      interface: virtio
    - size: 20GiB
      storage_domain: "{{ rhv_data_storage }}"
      name: localvol_disk
      interface: virtio

infra_vm:
  cluster: "{{ rhv_cluster }}"
  template: rhel7
  memory: 8GiB
  cores: 2
  disks:
    - size: 20GiB
      storage_domain: "{{ rhv_data_storage }}"
      name: docker_disk
      interface: virtio
    - size: 20GiB
      storage_domain: "{{ rhv_data_storage }}"
      name: localvol_disk
      interface: virtio

lb_vm:
  cluster: "{{ rhv_cluster }}"
  template: rhel7
  memory: 4GiB
  cores: 1

vms:
  # Node VMs
  - name: openshift-node01
    tag: openshift_node
    profile: "{{ node_vm }}"
    cloud_init:
      host_name: "openshift-node01.{{ local_hosted_zone }}"
      authorized_ssh_keys: "{{ root_ssh_key }}"
    nics:
      - name: nic1
        profile_name: ovirtmgmt
        interface: virtio
        mac_address: 00:1a:4a:16:01:49
  
  - name: openshift-node02
    tag: openshift_node
    profile: "{{ node_vm }}"
    cloud_init:
      host_name: "openshift-node02.{{ local_hosted_zone }}"
      authorized_ssh_keys: "{{ root_ssh_key }}"
    nics:
      - name: nic1
        profile_name: ovirtmgmt
        interface: virtio
        mac_address: 00:1a:4a:16:01:48
 
  # Infra VMs
  - name: openshift-infra1
    tag: openshift_infra
    profile: "{{ node_vm }}"
    cloud_init:
      host_name: "openshift-infra1.{{ local_hosted_zone }}"
      authorized_ssh_keys: "{{ root_ssh_key }}"
    nics:
      - name: nic1
        profile_name: ovirtmgmt
        interface: virtio
        mac_address: 00:1a:4a:16:01:47
 
  - name: openshift-infra2
    tag: openshift_infra
    profile: "{{ node_vm }}"
    cloud_init:
      host_name: "openshift-infra2.{{ local_hosted_zone }}"
      authorized_ssh_keys: "{{ root_ssh_key }}"
    nics:
      - name: nic1
        profile_name: ovirtmgmt
        interface: virtio
        mac_address: 00:1a:4a:16:01:46
 
  # Master VMs
  - name: openshift-master1
    profile: "{{ master_vm }}"
    tag: openshift_master
    cloud_init:
      host_name: "openshift-master1.{{ local_hosted_zone }}"
      authorized_ssh_keys: "{{ root_ssh_key }}"
    nics:
      - name: nic1
        profile_name: ovirtmgmt
        interface: virtio
        mac_address: 00:1a:4a:16:01:45
 
  - name: openshift-master2
    tag: openshift_master
    profile: "{{ master_vm }}"
    cloud_init:
      host_name: "openshift-master2.{{ local_hosted_zone }}"
      authorized_ssh_keys: "{{ root_ssh_key }}"
    nics:
      - name: nic1
        profile_name: ovirtmgmt
        interface: virtio
        mac_address: 00:1a:4a:16:01:44
 
  - name: openshift-master3
    tag: openshift_master
    profile: "{{ master_vm }}"
    cloud_init:
      host_name: "openshift-master3.{{ local_hosted_zone }}"
      authorized_ssh_keys: "{{ root_ssh_key }}"
    nics:
      - name: nic1
        profile_name: ovirtmgmt
        interface: virtio
        mac_address: 00:1a:4a:16:01:43
 
  # Load balancer
  - name: openshift-lb
    tag: openshift_lb
    profile: "{{ lb_vm }}"
    cloud_init:
      host_name: "openshift-lb.{{ local_hosted_zone }}"
      authorized_ssh_keys: "{{ root_ssh_key }}"
    nics:
    - name: nic1
      profile_name: ovirtmgmt
      interface: virtio
      mac_address: 00:1a:4a:16:01:50


affinity_groups:
  - name: masters_ag
    cluster: "{{ rhv_cluster }}"
    vm_enforcing: false
    vm_rule: negative
    vms:
      - openshift-master1
      - openshift-master2
      - openshift-master3
    wait: true
  - name: infra_ag
    cluster: "{{ rhv_cluster }}"
    vm_enforcing: false
    vm_rule: negative
    vms:
      - openshift-infra1
      - openshift-infra2
      - openshift-lb
    wait: true

  - name: app_ag
    cluster: "{{ rhv_cluster }}"
    vm_enforcing: false
    vm_rule: negative
    vms:
      - openshift-node01
      - openshift-node02
...
