---
# ----------------------------- Initial checks -------------------------------

# Check that the required variables are set
- assert:
    that: "{{ item }} is defined"
    msg: "Variable '{{ item }}' is mandatory to {{ role_action }} VDDK pluging."
  with_items:
    - v2v_build_dir
    - v2v_vddk_install_dir
    - v2v_vddk_package_name

# Include the check tasks, to avoid running the installation if not necessary
- include_tasks: check.yml

# If VDDK plugin is already installed and we have not set vddk_override, then skip.
- assert:
    msg: "nbdkit is already installed and 'v2v_vddk_override' is not set to true"
    that:
      - not v2v_nbdkit_plugin_working or v2v_vddk_override

- include_tasks: "repositories-{{ ansible_distribution | lower }}.yml"

- name: Ensure nbdkit packages are installed
  yum:
    name: "{{ item }}"
    state: "{{ v2v_yum_check }}"
  with_items:
    - nbdkit
    - nbdkit-plugin-python2

- name: Register nbdkit version
  shell: rpm -qa nbdkit | cut -d- -f2
  register: pkg_nbdkit

- include_tasks: "vddk-install.yml"

# With nbdkit before 1.2.4 we had to build our own version of VDDK plugin
- include_tasks: "nbdkit-plugin-vddk-rpm.yml"
  when:
    - pkg_nbdkit.stdout is version_compare('1.2.4', '<')

# With nbdkit 1.2.4 and newer we just make sure the package is installed
- name: Make sure VDDK plugin is installed
  yum:
    state: "{{ v2v_yum_check }}"
    name: nbdkit-plugin-vddk

- name: Install virt-v2v
  yum:
    state: "{{ v2v_yum_check }}"
    name: virt-v2v

- name: Install virt-v2v wrapper
  copy:
    src: "virt-v2v-wrapper.py"
    dest: "/usr/bin/"
    mode: 0755

- include_tasks: "validate-{{v2v_host_type}}.yml"
- include_tasks: "install-{{v2v_host_type}}.yml"
