---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Template Openshift hosts files
      template:
        src: hosts.j2
        dest: "{{ playbook_dir }}/inventory/hosts"
      run_once: true      
      tags:
        - hosts

    - local_action: meta
        refresh_inventory
      tags:
        - hosts

- include: "{{ playbook_dir }}/prerequisite.yaml"
  tags:
    - pre
    - rhsm

- hosts: nodes
  roles:
    - role: docker-storage-setup
      docker_dev: '/dev/vdb'
  tags:
    - pre
    - storage

- hosts: nodes:!masters
  roles:
    - role: openshift-volume-quota
      local_volumes_device: '/dev/vdc'
  tags:
    - pre
    - storage

- name: call openshift includes for installer
  include: /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
  tags:
    - byo
  #vars_file:
  #  ocp-vars.yml
- hosts: lb
  
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Install oc client
      yum:
        name: atomic-openshift-clients
        state: latest
      nofity: add cluster-admin
      tags: kube

    - name: copy kube config
      fetch:
        src: /root/.kube/config
        dest: /root/.kube/
        flat: yes
      delegate_to: "{{ groups.masters[0] }}"
      nofity: add cluster-admin
      tags: kube   

    - name: add cluster-admin
      shell: oc adm policy add-cluster-role-to-user cluster-admin admin
      tags: kube
