---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Template Openshift hosts files
      template:
        src: hosts.j2
        dest: "{{ playbook_dir }}/inventory/hosts"
      run_once: true      
      tags:
        - hosts

    - local_action: meta
        refresh_inventory
      tags:
        - hosts

- hosts: nodes:lb
  gather_facts: yes
  become: yes
  #serial: 1
  vars:
    rhsm_user: "{{ rhsub_user }}"
    rhsm_password: "{{ rhsub_password }}"
    rhsm_pool: "{{ rhsub_pool }}"
  roles:
    - role: rhsm-subscription
      when: openshift_deployment_type in ["enterprise", "atomic-enterprise", "openshift-enterprise"] and
            ansible_distribution == "RedHat" and ( rhsm_user is defined or rhsm_activation_key is defined)
    - role: rhsm-repos
      when: openshift_deployment_type in ["enterprise", "atomic-enterprise", "openshift-enterprise"] and
            ansible_distribution == "RedHat" and ( rhsm_user is defined or rhsm_activation_key is defined)

- hosts: nodes:!masters
  roles:
    - role: openshift-volume-quota
      local_volumes_device: '/dev/vdc'

- name: call openshift includes for installer
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

- name: add firewall rules to load balancer
  hosts: lb
  tasks:
    - name: Add 80/443  iptables rules
      iptables:
        chain: OS_FIREWALL_ALLOW
        state: present
        protocol: tcp
        match: state,tcp
        ctstate: NEW
        destination_port: "{{ item }}"
        jump: ACCEPT
      with_items:
        - 80
        - 443

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Install oc client
      yum:
        name: atomic-openshift-clients
        state: latest
      notify: 
        - add cluster-admin
      tags: kube

    - name: copy kube config
      fetch:
        src: /root/.kube/config
        dest: /root/.kube/
        flat: yes
      delegate_to: "{{ groups.masters[0] }}"
      notify: 
        - add cluster-admin
      tags: kube   

#    - name: hawkular fix adding view role
#      shell: oc adm policy add-role-to-user view system:serviceaccount:openshift-infra:hawkular -n openshift-infra
      
  handlers:
    - name: add cluster-admin
      shell: oc adm policy add-cluster-role-to-user cluster-admin admin
      notify: 
        - add cluster-admin
      tags: kube

