---
- name: add firewall rules to load balancer
  hosts: nodes
  vars:
    iptables_file: /etc/sysconfig/iptables
    ports:
      - 1936
      - 9100
  tasks:
    - name: Add iptables rules in memory
      iptables:
        chain: OS_FIREWALL_ALLOW
        state: present
        protocol: tcp
        match: state,tcp
        ctstate: NEW
        destination_port: "{{ item }}"
        jump: ACCEPT
      register: firewall
      with_items:
        - "{{ ports }}"
      notify: 
        - save firewall
        - restart logind

  handlers:
    - name: save firewall
      shell: service iptables save

    # https://github.com/openshift/openshift-ansible/pull/7888
    # dnsmasq / dbus issue
    # patched roles/openshift_node/tasks/dnsmasq_install.yml
    # restart logind to fix dbus disconnect after above patch. fixes slow logins/su's
    - name: restart logind
      systemd:
        state: restarted
        name: systemd-logind


