---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Template Openshift hosts files
      template:
        src: hosts.j2
        dest: "{{ playbook_dir }}/inventory/hosts"
      run_once: true
      tags:
        - hosts

    - local_action: meta
        refresh_inventory
      tags:
        - hosts

- hosts: nodes:lb
  gather_facts: yes
  become: yes
  roles:
  - rhsm-timeout

- hosts: nodes:lb
  gather_facts: no
  become: yes
  #serial: 1
  vars:
    rhsm_user: "{{ rhsub_user }}"
    rhsm_password: "{{ rhsub_password }}"
    rhsm_pool: "{{ rhsub_pool }}"
  roles:
  - role: rhsm-subscription
    when: openshift_deployment_type in ["enterprise", "atomic-enterprise", "openshift-enterprise"] and
          ansible_distribution == "RedHat" and ( rhsm_user is defined or rhsm_activation_key is defined)
  - role: rhsm-repos
    when: openshift_deployment_type in ["enterprise", "atomic-enterprise", "openshift-enterprise"] and
          ansible_distribution == "RedHat" and ( rhsm_user is defined or rhsm_activation_key is defined)
