- hosts: nodes:lb
  gather_facts: yes
  become: yes
  #serial: 1
  vars:
    rhsm_user: "{{ rhsub_user }}"
    rhsm_password: "{{ rhsub_password }}"
    rhsm_pool: "{{ rhsub_pool }}"
  roles:
    - role: rhsm-subscription
      when: openshift_deployment_type in ["enterprise", "atomic-enterprise", "openshift-enterprise"] and
            ansible_distribution == "RedHat" and ( rhsm_user is defined or rhsm_activation_key is defined)
    - role: rhsm-repos
      when: openshift_deployment_type in ["enterprise", "atomic-enterprise", "openshift-enterprise"] and
            ansible_distribution == "RedHat" and ( rhsm_user is defined or rhsm_activation_key is defined)

